apiVersion: apps/v1
kind: Deployment
metadata:
  name: items-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: items
  template:
    metadata:
      labels:
        app: items
    spec:
      containers:
        - name: items
          image: sujandkripadas/items-deploy
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5002
